### ISSUE TITLE
Can this run on Mobile? 

### ISSUE THREAD

**Issue by InternetMaster1** [Yaoyi-Li/HOP-Matting#2]
Can this or GCA matting be run on Mobile? Is it possible to change the backbone to mobilenet? 

Something similar to this library which convert Deep Matting into mobile friendly (but SAD score isn't very good) 
https://github.com/foamliu/Mobile-Image-Matting

I am aware of IndexNet Matting library, but their license is restrictive for commercial purpose.

**Comment by Yaoyi-Li** [comment]
We have never tried to run this propoagation based matting with a lightweight backbone. Based on the results  of IndexNet, maybe it works fine.  But it is still a a time-consuming task even if you use a lightweight backbone due to the propagation part.

P.S. You remind me that this pretrained model is also covered by Adobe's license.

**Comment by InternetMaster1** [comment]
Thank you...

Yes, I do not intend to use pretrained model
